[2025-08-29T18:50:27.115+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:10:00+00:00 [queued]>
[2025-08-29T18:50:27.275+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:10:00+00:00 [queued]>
[2025-08-29T18:50:27.281+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:27.282+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T18:50:27.304+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T18:50:28.319+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-07-05 02:10:00+00:00
[2025-08-29T18:50:28.599+0000] {standard_task_runner.py:52} INFO - Started process 435 to run task
[2025-08-29T18:50:28.803+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-07-05T02:10:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmpnr3_7f6x', '--error-file', '/tmp/tmpqcsehl73']
[2025-08-29T18:50:28.958+0000] {standard_task_runner.py:80} INFO - Job 238: Subtask preprocess_data
[2025-08-29T18:50:36.959+0000] {task_command.py:371} INFO - Running <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-07-05T02:10:00+00:00 [running]> on host b40c5a90b1e4
[2025-08-29T18:50:56.551+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Muhammad Al Ghifari
AIRFLOW_CTX_DAG_ID=etl_P2M3_muhammad_al_ghifari
AIRFLOW_CTX_TASK_ID=preprocess_data
AIRFLOW_CTX_EXECUTION_DATE=2025-07-05T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-07-05T02:10:00+00:00
[2025-08-29T18:51:06.380+0000] {logging_mixin.py:115} INFO - Preprocessed data is Success
[2025-08-29T18:51:12.187+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T18:51:13.418+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 435. PIDs of all processes in the group: [435]
[2025-08-29T18:51:13.516+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 435
[2025-08-29T18:51:13.794+0000] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-29T18:51:15.324+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/P2M3_muhammad_al_ghifari_DAG.py", line 161, in preprocess_data
    print(df.head())
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1002, in __repr__
    show_dimensions=show_dimensions,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1134, in to_string
    line_width=line_width,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1053, in to_string
    string = string_formatter.to_string()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/string.py", line 25, in to_string
    text = self._get_string_representation()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/string.py", line 49, in _get_string_representation
    return self._fit_strcols_to_terminal_width(strcols)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/string.py", line 194, in _fit_strcols_to_terminal_width
    strcols = self._get_strcols()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/string.py", line 31, in _get_strcols
    strcols = self.fmt.get_strcols()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 540, in get_strcols
    strcols = self._get_strcols_without_index()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 793, in _get_strcols_without_index
    str_columns = self._get_formatted_column_labels(self.tr_frame)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 841, in _get_formatted_column_labels
    from pandas.core.indexes.multi import sparsify_labels
  File "<frozen importlib._bootstrap>", line 1009, in _handle_fromlist
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1555, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-29T18:51:15.588+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250705T021000, start_date=20250829T185027, end_date=20250829T185115
[2025-08-29T18:51:16.365+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 238 for task preprocess_data (Task received SIGTERM signal; 435)
[2025-08-29T18:51:16.568+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=435, status='terminated', exitcode=1, started='18:50:28') (435) terminated with exit code 1
[2025-08-29T18:51:16.675+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T18:51:17.859+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
