[2025-08-29T19:03:41.584+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-02T02:30:00+00:00 [queued]>
[2025-08-29T19:03:41.693+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: etl_P2M3_muhammad_al_ghifari.preprocess_data scheduled__2025-08-02T02:30:00+00:00 [queued]>
[2025-08-29T19:03:41.712+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:41.746+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-08-29T19:03:41.751+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-08-29T19:03:42.148+0000] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): preprocess_data> on 2025-08-02 02:30:00+00:00
[2025-08-29T19:03:42.562+0000] {standard_task_runner.py:52} INFO - Started process 282 to run task
[2025-08-29T19:03:42.672+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_P2M3_muhammad_al_ghifari', 'preprocess_data', 'scheduled__2025-08-02T02:30:00+00:00', '--job-id', '274', '--raw', '--subdir', 'DAGS_FOLDER/P2M3_muhammad_al_ghifari_DAG.py', '--cfg-path', '/tmp/tmp0hppjcll', '--error-file', '/tmp/tmpb_13hnzs']
[2025-08-29T19:03:42.777+0000] {standard_task_runner.py:80} INFO - Job 274: Subtask preprocess_data
[2025-08-29T19:03:43.196+0000] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2025-08-29T19:03:43.263+0000] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 282. PIDs of all processes in the group: [282]
[2025-08-29T19:03:43.273+0000] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 282
[2025-08-29T19:03:43.849+0000] {process_utils.py:75} INFO - Process psutil.Process(pid=282, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:03:42') (282) terminated with exit code Negsignal.SIGTERM
[2025-08-29T19:03:43.853+0000] {local_task_job.py:156} INFO - Task exited with return code 143
[2025-08-29T19:03:44.458+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=etl_P2M3_muhammad_al_ghifari, task_id=preprocess_data, execution_date=20250802T023000, start_date=20250829T190341, end_date=20250829T190344
[2025-08-29T19:03:48.853+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
